### ISSUE TITLE
Reversing a credential id

### ISSUE THREAD

**Issue by aolney** [dlenski/python-vipaccess#21]
I have an existing hardware token already registered with various sites. 

Is it possible to use this library to replace the token just using the "credential id" such that the OTP codes generated would be identical to those produced by the token?

**Comment by aph3rson** [comment]
Right off the bat, I'd imagine not.

Looking at the code, this library wraps a request to the VIP provisioning service - this allows for the registration of a newly-created credential, including the prefix. There's no call in this service to get the secret behind an existing credential ID. This is likely by design, as it would be trivially easy to "borrow" someone else's physical token, take a picture of the credential ID on the back, and you've now cloned their second factor.

**Comment by dlenski** [comment]
> Is it possible to use this library to replace the token just using the "credential id" such that the OTP codes generated would be identical to those produced by the token?

**No.** @aph3rson is precisely right:

> This is likely by design, as it would be trivially easy to "borrow" someone else's physical token, take a picture of the credential ID on the back, and you've now cloned their second factor.

If this were possible, it'd mean that it's possible to obtain the secret seed using _just_ the token ID, which would be a massive security flaw.
