### ISSUE TITLE
Packaging for PyPI and conda

### ISSUE THREAD

**Issue by kynan** [dlenski/python-vipaccess#24]
I would like to package `python-vipaccess` for `conda` (on https://conda-forge.org). Could you please tag a new release?

Out of interest: what's the rationale for jumping to 0.9.0 from 0.3.6?

**Comment by kynan** [comment]
Have you already reached out to @cyrozap for taking over the PyPI package?

**Comment by dlenski** [comment]
Done, tagged as [v0.10.0](https://github.com/dlenski/python-vipaccess/releases/tag/v0.10.0).

I think I pinged @cyrozap shortly after I forked the project (driven by a need for `VSMT` tokens rather than `VSST`) a couple years ago. Would be good to hear his thoughts — whether it's a "go ahead and take it over" or an "aaghhh!" :grin:

**Comment by dlenski** [comment]
After some more prodding over at #28, I ~flailed around for a while trying to build a working page and then finally~ built a working [v0.10.2](https://github.com/dlenski/python-vipaccess/releases/tag/v0.10.0) which is now on PyPI.
