### ISSUE TITLE
Request specific ID?

### ISSUE THREAD

**Issue by NeighborGeek** [dlenski/python-vipaccess#29]
Is it possible to specify not just a prefix, but an entire OATH token ID to use when requesting a VIP credential?  

I'm using this tool to create HOTP credentials which will be programmed to Yubikeys.  I've been successfully creating tokens using Yubikey's OMP and token type Prefix of UBHE.  

By default, Yubikeys have an OATH ID of UBHE followed by the serial number printed on the key.  It would be ideal if I could request a VIP Credential with that OATH ID, so that the VIP Token's ID matches what is printed on the key.  As it works currently, because the VIP Credential service assigns an ID for the credential which doesn't match the serial number on the key, there is no way to tell the VIP Token ID from looking at the key.  After a key is programmed I have to maintain a list to cross-reference the key's serial number to the VIP Token ID which was programmed to it, so that we have the token ID to enter when adding a key to a user's account. 

Does the VIP service support requesting a specific OATH ID, and if so could that functionality be added to this tool?

**Comment by dlenski** [comment]
> Is it possible to specify not just a prefix, but an entire OATH token ID to use when requesting a VIP credential?

Interesting use case. As far as I know, it is _not_ possible to request a credential with a specific identifier.

This would be a possible security hole; if you could plan to expect a specific security token ID in advance, then someone else could possibly see that ID and register it before you could, thereby potentially being able to use their token in place of yours. (Depends on various details of the provisioming and authentication process for whether this would really work.)

**Comment by luv2dnce33** [comment]
Came here looking for this exactly. This should absolutely be possible given the architecture of how Symantec VIP protocol works https://www.cyrozap.com/2014/09/29/reversing-the-symantec-vip-access-provisioning-protocol/

Maybe @cyrozap can comment more on it.

**Comment by cyrozap** [comment]
> This should absolutely be possible given the architecture of how Symantec VIP protocol work

@luv2dnce33, I'm not sure what part of my blog post caused you to think this is possible, but I apologize if I gave that impression because that's almost certainly not correct. I base my reasoning on the fact that none of the fields in the provisioning request contain any kind of token ID, and that it would be a tremendous security vulnerability if a user could clone/DoS someone else's token simply by knowing their token ID.

That said, it _is_ possible to specify the token model, as explained in [the README](https://github.com/dlenski/python-vipaccess/blob/e7b0fb35adf4ebc991c8e44d423d7b4801ea721d/README.md#provisioning-a-new-vip-access-credential), so maybe that's what you were thinking of when you said this should be possible?

**Comment by dlenski** [comment]
Closing this, since the requested functionality is almost certainly impossible to achieve. It'd be a huge security hole as both @cyrozap and I have pointed out.
