### ISSUE TITLE
Say what to do when big company says download the app...

### ISSUE THREAD

**Issue by jidanni** [dlenski/python-vipaccess#37]
Please add a section saying what to do when [a big company says](https://www.fidelity.com/security/soft-tokens/overview)
- Step 1: Download the [Symantec] app
- Step 2: Call us

I mean I know how to do
```
oathtool -b --totp AAA...
```
just fine. I just don't understand what I should say to the man on the phone. Is he going to tell me some code that I would have typed into the app, but instead put in a file?

Or should I install the proprietary app just once, then after which I can remove it?

**Comment by jidanni** [comment]
OK, maybe it's [like](https://locima.com/2019/06/01/replacing-symantec-vip-with-a-generic-totp-app/)
1. I install and run python-vipaccess
1. It generates VSMT22195338 and SS3MEAKIB...
1. I call the man and tell him the former, afterwhich I can use the latter in oathtool.

**Comment by jidanni** [comment]
(I suppose if I instead just installed the Symantec app I would never be able to squeeze SS3MEAKIB... out of it to use in oathtool, etc.)

**Comment by dlenski** [comment]
Not sure what you're asking for here.

Yes, if you're using `python-vipaccess` and you're talking to some customer service robo-human who expects you're using the official Symantec app, you'll probably have to “translate” from what they're asking you to do, and you'll probably have to “pretend” that you're using the official app in order to avoid scaring them off (“sir, we don't support Lie-nucks because securiteh”).

> 1. I install and run python-vipaccess
> 2. It generates VSMT22195338 and SS3MEAKIB...
> 3. I call the man and tell him the former (VS..), after which I can use the latter (SS...) in oathtool happily ever after (to generate 30 second codes.)

Yes, that sounds about right. You run `vipaccess provision -p`, it generates a credential ID (`VSwhatever`) and a secret (base32 string). You give them the credential ID, and then use the secret to generate the codes.

Although it's _possible_ that when you're on the phone with them, they tell you to go to \[some URL that we don't yet know about\], which launches the official Symantec VIP access app into \[some mode that we don't yet know about\] which provisions a token in \[some other way\]. Soft-token apps are always adding new layers of stupid ([glorious example here](https://github.com/dlenski/rsa_ct_kip)) to their provisioning processes, in order to make them work better. If this happens, tell us about it and maybe we can figure out how to de-cruft it.

**Comment by jidanni** [comment]
(Ah, reminds me about having to [dig ones codes out of Authy](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93), [etc.](https://github.com/beemdevelopment/Aegis/issues/138)

**Comment by jidanni** [comment]
We see at https://vip.symantec.com/ we can test if vipaccess is working...

**Comment by jidanni** [comment]
Okay I installed the official app and called the big company,  first  they went over a giant bunch of questions to make sure it was really me, and then they just simply asked me the number shown on the screen that starts with a "s y m c", as you can see in the first picture of https://play.google.com/store/apps/details?id=com.verisign.mvip.main

**Comment by jidanni** [comment]
Okay, some things I noted. First the official app always gives you 30 seconds to use the 6 digit number number it creates.  other apps won't always start at the beginning of the 30 seconds naturally, but this app does for some reason. Second, this app only has one six digit number for all sites, instead one for company A a different one for company B excetera excetera Of course I'm talking not about the extra sites that one added in by a QR code.

**Comment by jidanni** [comment]
In conclusion, I just don't understand how telling the big company that 8 digit number is enough get things going. Certainly the app has also sent something behind my back to the big company directly or indirectly, that I'm afraid that this GitHub project just probably doesn't have any way to send them. Of course I'm too timid to experiment.

**Comment by jidanni** [comment]
I also don't understand how vendor lock-in benefits the big company. Certainly one day a botched update to the app from Symantec or something else won't compromise anybody's money, but at least it will probably lock people out of their accounts.

**Comment by jidanni** [comment]
Indeed, the current app makes SYMCdddddddd codes probably reflecting the change in ownership from the former V... company codes...

So, what if the man asked me what is the problem with my app? Well I would how to say I... I guess I'm using an older version I got somewhere.
A couple weird responses and I'll probably have the FBI knocking on my door.

**Comment by jidanni** [comment]
Anyway, another area you might direct your attention to is squeezing out the TOTP key out of the guts of the app, like they did with Authy.
Might need root on Android, or need their desktop app.

**Comment by dlenski** [comment]
> We see at https://vip.symantec.com/ we can test if vipaccess is working...

`vipaccess provision` does this automatically right after creating a new token.

>  and then they just simply asked me the number shown on the screen that starts with a "s y m c", as you can see in the first picture of https://play.google.com/store/apps/details?id=com.verisign.mvip.main

So what's the problem? You can generate a SYMC token using ` vipaccess provision -p -t SYMC`…

```
Generating request...
Fetching provisioning response...
Getting token from response...
Decrypting token...
Checking token...
Credential created successfully:
	otpauth://totp/VIP%20Access:SYMC39528718?secret=WIRBRWFK3JH5NIIXJLUDRL7NKXVKD4GV&digits=6&period=30&issuer=Symantec&algorithm=SHA1
This credential expires on this date: 2023-05-10T16:53:55.843Z
```

> Okay, some things I noted. First the official app always gives you 30 seconds to use the 6 digit number number it creates. other apps won't always start at the beginning of the 30 seconds naturally, but this app does for some reason. 

What is "this app"? `python-vipaccess` or the official app?

The fact that the official app will give you 30s no matter when you open it is a UI difference, not an underlying difference in the algorithm… it just means that the consumers of the code will accept up to a 30s offset. :man_shrugging: 

> Certainly the app has also sent something behind my back to the big company directly or indirectly, that I'm afraid that this GitHub project just probably doesn't have any way to send them.

No. You should actually _try this_ all the way through before jumping to such conclusions.

There is no need for anything to be magically exchanged behind your back…

1. You provision at token. Now you know the ID and the secret, and Symantec knows both as well.
2. You give the token ID to Fidelity.
3. You tell Fidelity the current 6-digit code. They don't know the secret but they can verify that this is the current code for this token using Symantec's test site (more realistically, they use the actual API that Symantec gives to enterprise customers).
4. So now Fidelity believes you have that token, associates it with your account, and uses that same API from Symantec to verify the correctness of the codes every time you log in.

No secret exchange needed.

>  Of course I'm too timid to experiment.
> A couple more weird responses and I'll probably have the FBI knocking on my door.

Yes, you are too timid.

How do you think these tools (`python-vipaccess` and `rsa_ct_kip` and [`smxlogin`](https://github.com/dlenski/smxlogin), etc.) were developed?

By giving a gazillion "wrong responses" until we figured out how to give the right ones. By emailing/calling IT departments a gazillion times and saying "oops, my token app stopped working, can you issue me a new one?"

I am not a lawyer, but I see no reason to think any of this is illegal. We are not trying to hack into anyone else's account. We are simply developing tools to be able to access our own account information.

**Comment by jidanni** [comment]
(By app I meant official app.) (Fidelity never asked for the current six digit code (which indeed yes worked to login later,) only the SYMCdddddddd code.) OK thanks. I'll close this issue.

**Comment by dlenski** [comment]
> Fidelity never asked for the current six digit code (which indeed yes worked to login later,) only the SYMCdddddddd code.

That's kind of hilarious/stupid/sad, because it means that if you conveyed the token ID to them incorrectly (easy to do over the phone, right?) they would've linked your account to the wrong token. So much for the alleged higher securiteh of doing this over the phone. :man_facepalming: 

And well done :+1:. Maybe you should write the official guide to setting up Fidelity with `python-vipaccess`… as others have already done [for PayPal](https://semjonov.de/post/2018-03/set-up-2fa-app-for-paypal/) and other services.

**Comment by jidanni** [comment]
Sure... except that I still haven't even installed pip, etc.
Mom said not to test with grandpa's retirement account.

**Comment by jidanni** [comment]
> > We see at https://vip.symantec.com/ we can test if vipaccess is working...
> 
> `vipaccess provision` does this automatically right after creating a new token.

Huh, your program makes an HTTP request, and to Symantec? Better warn about that on README.md if indeed the case.

**Comment by dlenski** [comment]
> Huh, your program makes an HTTP request, and to Symantec? 

HTTPS, not HTTP.

Uh… huh… what!?  ¯\\\_\(ツ\)\_/¯

**Of course** it has to communicate with Symantec (entirely over TLS/HTTPS) to provision a new token. As I wrote above:

> 1. You provision a token. Now you know the ID and the secret, and **Symantec knows both as well.**

The whole point of this is that Symantec is doing the 2-factor authentication on behalf of \[some other service\], e.g. Fidelity or Paypal. 

Are you sure you understand how this works?

**Comment by jidanni** [comment]
OK but on README.md it needs to say explicitly that the program needs to
connect to Symantec, else one assumes the program must be some frontend
to oathtool, etc. that works offline.

**Comment by dlenski** [comment]
> OK but on README.md it needs to say explicitly that the program needs to
connect to Symantec,

No it doesn't. Hundreds of people have used this program, if not more; literally no one has ever expressed surprise that it talks to the Symantec server, because they all understand that that's _the whole point_ of provisioning a new token.

You seem to have a surprisingly complex mental model of what this program _might do_, without any experience _actually does_.

`vip provision` connects to https://services.vip.symantec.com and says "please give me a new token with prefix ABCD"… the server says "here you go" and gives back the token in a slightly-obfuscated format. No remotely-interesting or privacy-sensitive information is sent to the server. You can run this process 100 times a day… the FBI won't come knocking on your door… the [Taiwan National Security Bureau](https://en.wikipedia.org/wiki/National_Security_Bureau_(Taiwan)) won't have any questions… your credit rating will not be affected… your cat or dog will not feel any lingering health effects. Understand?

Try using it and then give me some cogent feedback based on reality.

I'll happily accept pull requests to explain the program's behavior more clearer, but they need to be based on reality.
