### ISSUE TITLE
Not working on PayPal?

### ISSUE THREAD

**Issue by Daniel15** [dlenski/python-vipaccess#5]
I used `python vipaccess\cli.py provision -p -t VSMT` to generate a credential `VSMT917*****` and added it to Authy on my phone. That worked fine. However, when I try to add it to my PayPal account, I get this error message after entering the serial number and two codes:

![](http://ss.dan.cx/2017/04/Please_Contact_Customer_Service_-_PayPal_-_Google__23-16.13.19.png)

Any ideas?

**Comment by dlenski** [comment]
I tried setting it up myself (via https://www.paypal.com/us/cgi-bin/webscr?cmd=_setup-security-key) and it appeared to work just fine.

(I tried both VSST and VSMT "token models". And they **both** worked fine.)

**Comment by dlenski** [comment]
@Daniel15, still having the problem?

**Comment by Daniel15** [comment]
Yeah, still broken for me. I tried searching and only found a single post with someone else hitting the same error message, with no responses: https://www.paypal-community.com/t5/About-Protections/Problems-authenticating-2FA-token/td-p/1184369

Oh well. I blame PayPal rather than your script. I wanted to get rid of VeriSign VIP and just use Authy, but I guess I'll keep the VeriSign app installed for now.

**Comment by dlenski** [comment]
1. It might be worth trying again with VSST instead of VSMT…?
2. Are you 100% sure that your system clock is perfectly synced? If it's off by >~15 seconds, then the trial token values that you input to authorize the token won't work.

**Comment by Daniel15** [comment]
> It might be worth trying again with VSST instead of VSMT…?

I tried both 😢 

> Are you 100% sure that your system clock is perfectly synced? 

Yeah... I tested on both my phone (via the Authy app) and my computer (via the Authy Chrome extension), and other sites that use two-factor auth are fine. I don't know of any other sites that use VeriSign VIP Access though, so I'm not sure how to test it specifically.

**Comment by Ishfal** [comment]
For what it's worth, I have a theory (that is bearing out in testing) as to why Paypal is not working. 

I first set up VIP Access tokens last year using dlenski's code. At that time, tokens generated both on my phone (using FreeOTP) and PC (using Keepass) worked with Paypal. However, over time the phone codes ceased being accepted and only the PC codes worked.

My PC, which is on Windows 10, shows a time (which is purportedly synced to time.windows.com) that is ~4 minutes behind the actual time. When I force my phone's clock to match my PC's time, the OTP codes generated there match those on my PC (as they should) and are accepted by Paypal.

So, my theory is that Paypal (or perhaps Symantec on the backend) may also be using time.windows.com (which has been having sync issues for a while) and so are generating different OTP codes than a correctly synced clock would generate.

**Comment by dlenski** [comment]
> My PC, which is on Windows 10, shows a time (which is purportedly synced to time.windows.com) that is ~4 minutes behind the actual time. When I force my phone's clock to match my PC's time, the OTP codes generated there match those on my PC (as they should) and are accepted by Paypal.
>
> So, my theory is that Paypal (or perhaps Symantec on the backend) may also be using time.windows.com (which has been having sync issues for a while) and so are generating different OTP codes than a correctly synced clock would generate.

Woah… that is _so crazy it might be true_. So the theory here is that `time.windows.com` has been off by **4 minutes** since a while back?!!?!

Apparently the track record of `time.windows.com` in this regard is…
 terrible! https://www.bleepingcomputer.com/news/microsoft/windows-ntp-time-service-sends-wrong-time-to-users-worldwide/

**Comment by dlenski** [comment]
Hmmm… I ran `ntpdate` against both `time.windows.com` and `ntp.ubuntu.com`, and they both appear to be perfectly accurate, with offsets of <.1 seconds relative to my laptop:

```sh
$ ntpdate -dv time.windows.com
 7 Jan 18:12:50 ntpdate[10848]: ntpdate 4.2.8p4@1.3265-o Thu Sep  7 20:43:11 UTC 2017 (1)
Looking for host time.windows.com and service ntp
host found : 13.65.245.138
transmit(13.65.245.138)
receive(13.65.245.138)
transmit(13.65.245.138)
receive(13.65.245.138)
transmit(13.65.245.138)
receive(13.65.245.138)
transmit(13.65.245.138)
receive(13.65.245.138)
server 13.65.245.138, port 123
stratum 2, precision -23, leap 00, trust 000
refid [13.65.245.138], delay 0.10501, dispersion 0.00201
transmitted 4, in filter 4
reference time:    ddfd51f6.c07aa186  Sun, Jan  7 2018 18:12:06.751
originate timestamp: ddfd5239.04933d5f  Sun, Jan  7 2018 18:13:13.017
transmit timestamp:  ddfd5238.fd77365c  Sun, Jan  7 2018 18:13:12.990
filter delay:  0.10509  0.11386  0.10812  0.10501 
         0.00000  0.00000  0.00000  0.00000 
filter offset: -0.01230 -0.01475 -0.01790 -0.01193
         0.000000 0.000000 0.000000 0.000000
delay 0.10501, dispersion 0.00201
offset -0.011934

 7 Jan 18:13:13 ntpdate[10848]: adjust time server 13.65.245.138 offset -0.011934 sec

dlenski@dlenski-fps:~$ ntpdate -d ntp.ubuntu.com
 7 Jan 18:16:01 ntpdate[10957]: ntpdate 4.2.8p4@1.3265-o Thu Sep  7 20:43:11 UTC 2017 (1)
Looking for host ntp.ubuntu.com and service ntp
91.189.89.199 reversed to golem.canonical.com
host found : golem.canonical.com
transmit(91.189.89.199)
transmit(91.189.91.157)
receive(91.189.89.199)
receive(91.189.91.157)
transmit(91.189.89.198)
transmit(91.189.94.4)
receive(91.189.89.198)
receive(91.189.94.4)
transmit(91.189.89.199)
transmit(91.189.91.157)
receive(91.189.91.157)
receive(91.189.89.199)
transmit(91.189.89.198)
receive(91.189.89.198)
transmit(91.189.94.4)
receive(91.189.94.4)
transmit(91.189.89.199)
transmit(91.189.91.157)
receive(91.189.91.157)
receive(91.189.89.199)
transmit(91.189.89.198)
receive(91.189.89.198)
transmit(91.189.94.4)
receive(91.189.94.4)
transmit(91.189.89.199)
transmit(91.189.91.157)
receive(91.189.91.157)
receive(91.189.89.199)
transmit(91.189.89.198)
receive(91.189.89.198)
transmit(91.189.94.4)
receive(91.189.94.4)
server 91.189.89.199, port 123
stratum 2, precision -24, leap 00, trust 000
refid [91.189.89.199], delay 0.18636, dispersion 0.01128
transmitted 4, in filter 4
reference time:    ddfd4d4a.e6ede943  Sun, Jan  7 2018 17:52:10.902
originate timestamp: ddfd5300.5e9dd29b  Sun, Jan  7 2018 18:16:32.369
transmit timestamp:  ddfd5300.49826ff6  Sun, Jan  7 2018 18:16:32.287
filter delay:  0.22826  0.18674  0.18636  0.25029 
         0.00000  0.00000  0.00000  0.00000 
filter offset: -0.02252 -0.00017 0.002079 -0.02994
         0.000000 0.000000 0.000000 0.000000
delay 0.18636, dispersion 0.01128
offset 0.002079

server 91.189.91.157, port 123
stratum 2, precision -23, leap 00, trust 000
refid [91.189.91.157], delay 0.11691, dispersion 0.00818
transmitted 4, in filter 4
reference time:    ddfd4dea.8ef8d6b8  Sun, Jan  7 2018 17:54:50.558
originate timestamp: ddfd5300.594fa283  Sun, Jan  7 2018 18:16:32.348
transmit timestamp:  ddfd5300.498560f1  Sun, Jan  7 2018 18:16:32.287
filter delay:  0.11691  0.12529  0.12668  0.24998 
         0.00000  0.00000  0.00000  0.00000 
filter offset: -0.00101 0.000730 0.003529 -0.05053
         0.000000 0.000000 0.000000 0.000000
delay 0.11691, dispersion 0.00818
offset -0.001012

server 91.189.89.198, port 123
stratum 2, precision -24, leap 00, trust 000
refid [91.189.89.198], delay 0.18698, dispersion 0.00964
transmitted 4, in filter 4
reference time:    ddfd5171.775c258f  Sun, Jan  7 2018 18:09:53.466
originate timestamp: ddfd5300.f7990d04  Sun, Jan  7 2018 18:16:32.967
transmit timestamp:  ddfd5300.e2fa76f2  Sun, Jan  7 2018 18:16:32.886
filter delay:  0.22812  0.18843  0.31476  0.18698 
         0.00000  0.00000  0.00000  0.00000 
filter offset: -0.02242 -0.00070 -0.03083 -0.00019
         0.000000 0.000000 0.000000 0.000000
delay 0.18698, dispersion 0.00964
offset -0.000192

server 91.189.94.4, port 123
stratum 2, precision -23, leap 00, trust 000
refid [91.189.94.4], delay 0.18172, dispersion 0.04573
transmitted 4, in filter 4
reference time:    ddfd51f6.4da3529b  Sun, Jan  7 2018 18:12:06.303
originate timestamp: ddfd5301.909d1959  Sun, Jan  7 2018 18:16:33.564
transmit timestamp:  ddfd5301.7c93ed7b  Sun, Jan  7 2018 18:16:33.486
filter delay:  0.32088  0.47633  0.22662  0.18172 
         0.00000  0.00000  0.00000  0.00000 
filter offset: -0.06917 -0.13931 -0.02178 0.000178
         0.000000 0.000000 0.000000 0.000000
delay 0.18172, dispersion 0.04573
offset 0.000178

 7 Jan 18:16:33 ntpdate[10957]: adjust time server 91.189.91.157 offset -0.001012 sec
```

**Comment by dlenski** [comment]
> If @Ishfal is correct, then you should be able to test it with oathtool by skewing the time backwards by 240 seconds. (The base32 token secret is in your ~/.vipaccess.)

I just tested this and it **does not work**.

I enrolled my key with PayPal using the tokens from (4 minutes ago), and it didn't work.

I tried re-enrolling my key with PayPal using the tokens from (actual current time), and it did work.

So it's an interesting theory, but doesn't appear to be correct.

**Comment by Daniel15** [comment]
So I just tried this again recently (a few weeks ago), and it seemed to work fine this time. Hmm. o_O

**Comment by Ishfal** [comment]
Hmm, well thank you for the additional digging. Now I'm totally puzzled why PayPal is accepting tokens generated based on the wrong time for me, and rejecting them when generated using the right time.

Next weekend I'll mess around with oathtool and see if I can reproduce.

**Comment by Ishfal** [comment]
Just re-enrolled the key and it is working fine now. The issue must just have been due to drift over time. That key had originally been enrolled ~1.5 years ago, for whatever that's worth.

**Comment by aitte2** [comment]
I just want to confirm that I have never had any problems with this great tool! My token generated with `vipaccess provision -p -t VSMT` works perfectly at paypal. There's no problem with this library.

1. Be sure your system clock is perfectly synced. Enable internet time servers on your machine to be sure it's perfect!
2. When PayPal asks for a "device serial number" put the "VSMT...." device ID there.
3. In the two "enter two consecutive codes" fields enter two codes (you have to wait 30 seconds for the 2nd code). Generate them with any TOTP-compatible authentication app. I use 1Password, which has a super easy way to enter the authentication details (you just paste the "otpauth:" URL into a password field, as here https://support.1password.com/one-time-passwords/). Google authenticator and authy etc should work too since they also use TOTP.

Be sure to write down: Otpauth URL, token ID, and expiration date. Those are the 3 pieces of info that you'll need to have if you ever want to re-register your authenticator at PayPal.

**Comment by dlenski** [comment]
It appears that PayPal no longer offers the ability to add a new Symantec VIP token. The link that previously worked (https://www.paypal.com/cgi-bin/webscr?cmd=_security-token) now only offers the option to use SMS-based codes.

**Comment by aitte2** [comment]
@dlenski I set up my VIPAccess key yesterday and I can see the problem. You have the wrong URL.

I like writing instructions for myself and friends. Here is what I wrote down:

### About PayPal’s 2-Factor Authentication:

They don’t have direct support for things like Google Authenticator. But they have indirect support for it!

“Symantec VIP (VeriSign Identity Protection) Access” (now owned by Symantec but previously by VeriSign) uses the completely open TOTP standard for generating its 6-digit codes. The only proprietary part is the provisioning used for registering a new authenticator (which needs to contact the symantec server to register the “token device id”). That part of the protocol has luckily been reverse-engineered, which means that there’s no need to use their clunky, official Symantec apps.

1. First install the reverse engineered library, https://github.com/dlenski/python-vipaccess (it’s a fork which is maintained unlike the original). Read its installation instructions for a “manual build/install”. It’s really just these commands:

git clone https://github.com/dlenski/python-vipaccess.git
cd python-vipaccess
sudo pip3 install .

2. Now create your “Security Key” by running the following command which will register a token on the Symantec VIP Access server and output the final “otpauth” URL etc:

vipaccess provision -p -t VSMT

3. Save the otpauth URL, the expiry date, and the ID (which is the ID of the fake Symantec “device token” it generated). Put the otpauth URL in your OTP generator (I love 1Password!) so that you can start making tokens.

4. Go to https://www.paypal.com/webscr?cmd=_setup-security-key and click on the “Activate Security Key” choice.

5. Enter the generated token ID as the “Serial Number” and enter two consecutive 30-second codes.

6. From now on, every login at PayPal will require a single 2-factor code.

7. If you ever need to recover your account later, you can use the secret questions or receive a phone call at your registered number.

**Comment by aitte2** [comment]
Note to everyone:

http://www.bayareatechpros.com/symantec-vip-access-paypal/

According to the comments on that page, the theory is that PayPal doesn't "like" usage of the Symantec token because it breaks some PayPal payment forms on some webshops. So that's why PayPal has gone out of their way to hide the options. It used to be listed on the `_security-token` page but not anymore. Only the direct link works.

PayPal in 2018 still relying on SMS for payment verification is retarded. I hope they embrace full TOTP (Google Authenticator/Authy-style) soon.

**Comment by dlenski** [comment]
Thank you very much, @aitte2. As you wrote, PayPal has made it quite difficult to find the option to add a new Symantec VIP Access token.

**Comment by aitte2** [comment]
Yup. Still works for now. Hopefully forever (due to corporate needs or whatever). I can't receive SMS and I don't want to be fully unprotected. ;)

**Comment by dlenski** [comment]
> I can't receive SMS and I don't want to be fully unprotected. ;)

I hear you. I hate SMS-based 2FA with a passion due to the fact that I often can't get SMS when travelling internationally.

**Comment by aitte2** [comment]
@dlenski Haha that's my _exact_ reason for not being able to use SMS auth! ;) Anyway, thanks for maintaining this library. *knocks on wood that it will continue to work until PayPal inevitably implements regular TOTP*
