### ISSUE TITLE
spaces (%20) in issuer name causing problems?

### ISSUE THREAD

**Issue by nathanallen** [dlenski/python-vipaccess#53]
I'm seeing "token format not supported" if there are spaces in the `issuer` name (Authy on Android)

E.g.

```
# bad: Foo%20Bar
otpauth://totp/abcdefg:VSMT17814329?digits=6&secret=XXXX&period=30&algorithm=SHA1&issuer=Foo%20Bar

# good: FooBar
otpauth://totp/abcdefg:VSMT17814329?digits=6&secret=XXXX&period=30&algorithm=SHA1&issuer=FooBar
```

**Comment by dlenski** [comment]
That's Authy's fault. They work fine in [FreeOTP](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp).

Also, the closest thing there is to an official spec for `otpauth://` URIs is https://github.com/google/google-authenticator/wiki/Key-Uri-Format

Per [the issuer section](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer), the issuer in the _path_ (`ISSUER:VSMT1234982374`) should match the issuer in the query parameters (`&issuer=ISSUER`). I made python-vipaccess follow this convention in 5bb3ffeebc6d3278ae4010ff2806bacc873f2833.

Does putting spaces in the _path_ (and omitting `issuer` as a query parameter) work with Authy? For example, does _this_ work?

```
otpauth://totp/Foo%20Bar:VSMT17814329?digits=6&secret=XXXX&period=30&algorithm=SHA1
```

**Comment by nathanallen** [comment]
Yes, it appears to work fine with percent-encoded spaces in the path (and issuer omitted). The authy app displays it as: "Foo Bar: VSMT17814329".

**Comment by dlenski** [comment]
Per @beaufort2015 in #68:

> Lastly, it appears you no longer add the issuer= string to the credentials... why not? I added "&issuer=Charles%20Schwab" to the string to get a recognizable icon on the Authy app and it worked.

When this issue was initially opened, it appeared that Authy *cannot handle* spaces in the `issuer` query parameter of an `otpauth://` URI , but *can* handle them in the equivalent portion of the URI `path`, which is why I pushed https://github.com/dlenski/python-vipaccess/commit/acf264e20d90b73bd9b3bec330ccbbc958dc4420 as a fix.

Perhaps recent versions of Authy have fixed the spaces-in-`issuer` problem?
